//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Common.Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SingleFilmDS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SingleFilmDS : global::System.Data.DataSet {
        
        private vSingleFilmDataTable tablevSingleFilm;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public SingleFilmDS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected SingleFilmDS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["vSingleFilm"] != null)) {
                    base.Tables.Add(new vSingleFilmDataTable(ds.Tables["vSingleFilm"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public vSingleFilmDataTable vSingleFilm {
            get {
                return this.tablevSingleFilm;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            SingleFilmDS cln = ((SingleFilmDS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["vSingleFilm"] != null)) {
                    base.Tables.Add(new vSingleFilmDataTable(ds.Tables["vSingleFilm"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablevSingleFilm = ((vSingleFilmDataTable)(base.Tables["vSingleFilm"]));
            if ((initTable == true)) {
                if ((this.tablevSingleFilm != null)) {
                    this.tablevSingleFilm.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "SingleFilmDS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/SingleFilmDS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablevSingleFilm = new vSingleFilmDataTable();
            base.Tables.Add(this.tablevSingleFilm);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializevSingleFilm() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SingleFilmDS ds = new SingleFilmDS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void vSingleFilmRowChangeEventHandler(object sender, vSingleFilmRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class vSingleFilmDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnfldFilmID;
            
            private global::System.Data.DataColumn columnfldFarsiName;
            
            private global::System.Data.DataColumn columnfldEnglishName;
            
            private global::System.Data.DataColumn columnfldActors;
            
            private global::System.Data.DataColumn columnfldDirector;
            
            private global::System.Data.DataColumn columnfldYearsOfProduct;
            
            private global::System.Data.DataColumn columnfldIMDBRating;
            
            private global::System.Data.DataColumn columnfldPoster;
            
            private global::System.Data.DataColumn columnfldAbstract;
            
            private global::System.Data.DataColumn columnfldInformation;
            
            private global::System.Data.DataColumn columnfldSumVotes;
            
            private global::System.Data.DataColumn columnfldCountVotes;
            
            private global::System.Data.DataColumn columnfldSection;
            
            private global::System.Data.DataColumn columnfldTime;
            
            private global::System.Data.DataColumn columnfldfk_KindOfferID;
            
            private global::System.Data.DataColumn columnfldKindOfferName;
            
            private global::System.Data.DataColumn columnfldfk_CountryProductID;
            
            private global::System.Data.DataColumn columnfldCountryProductName;
            
            private global::System.Data.DataColumn columnfldfk_QualityID;
            
            private global::System.Data.DataColumn columnfldQualityName;
            
            private global::System.Data.DataColumn columnfldfk_RankID;
            
            private global::System.Data.DataColumn columnfldRankName;
            
            private global::System.Data.DataColumn columnfldPrice;
            
            private global::System.Data.DataColumn columnfldComment;
            
            private global::System.Data.DataColumn columnfldLanguageID;
            
            private global::System.Data.DataColumn columnfldLanguageName;
            
            private global::System.Data.DataColumn columnfldGenreID;
            
            private global::System.Data.DataColumn columnfldGenreName;
            
            private global::System.Data.DataColumn columnfldSubtitlesID;
            
            private global::System.Data.DataColumn columnfldSubtitlesName;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmDataTable() {
                this.TableName = "vSingleFilm";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal vSingleFilmDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected vSingleFilmDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldFilmIDColumn {
                get {
                    return this.columnfldFilmID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldFarsiNameColumn {
                get {
                    return this.columnfldFarsiName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldEnglishNameColumn {
                get {
                    return this.columnfldEnglishName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldActorsColumn {
                get {
                    return this.columnfldActors;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldDirectorColumn {
                get {
                    return this.columnfldDirector;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldYearsOfProductColumn {
                get {
                    return this.columnfldYearsOfProduct;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldIMDBRatingColumn {
                get {
                    return this.columnfldIMDBRating;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldPosterColumn {
                get {
                    return this.columnfldPoster;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldAbstractColumn {
                get {
                    return this.columnfldAbstract;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldInformationColumn {
                get {
                    return this.columnfldInformation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldSumVotesColumn {
                get {
                    return this.columnfldSumVotes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldCountVotesColumn {
                get {
                    return this.columnfldCountVotes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldSectionColumn {
                get {
                    return this.columnfldSection;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldTimeColumn {
                get {
                    return this.columnfldTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldfk_KindOfferIDColumn {
                get {
                    return this.columnfldfk_KindOfferID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldKindOfferNameColumn {
                get {
                    return this.columnfldKindOfferName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldfk_CountryProductIDColumn {
                get {
                    return this.columnfldfk_CountryProductID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldCountryProductNameColumn {
                get {
                    return this.columnfldCountryProductName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldfk_QualityIDColumn {
                get {
                    return this.columnfldfk_QualityID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldQualityNameColumn {
                get {
                    return this.columnfldQualityName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldfk_RankIDColumn {
                get {
                    return this.columnfldfk_RankID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldRankNameColumn {
                get {
                    return this.columnfldRankName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldPriceColumn {
                get {
                    return this.columnfldPrice;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldCommentColumn {
                get {
                    return this.columnfldComment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldLanguageIDColumn {
                get {
                    return this.columnfldLanguageID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldLanguageNameColumn {
                get {
                    return this.columnfldLanguageName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldGenreIDColumn {
                get {
                    return this.columnfldGenreID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldGenreNameColumn {
                get {
                    return this.columnfldGenreName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldSubtitlesIDColumn {
                get {
                    return this.columnfldSubtitlesID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fldSubtitlesNameColumn {
                get {
                    return this.columnfldSubtitlesName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmRow this[int index] {
                get {
                    return ((vSingleFilmRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event vSingleFilmRowChangeEventHandler vSingleFilmRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event vSingleFilmRowChangeEventHandler vSingleFilmRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event vSingleFilmRowChangeEventHandler vSingleFilmRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event vSingleFilmRowChangeEventHandler vSingleFilmRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddvSingleFilmRow(vSingleFilmRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmRow AddvSingleFilmRow(
                        long fldFilmID, 
                        string fldFarsiName, 
                        string fldEnglishName, 
                        string fldActors, 
                        string fldDirector, 
                        string fldYearsOfProduct, 
                        double fldIMDBRating, 
                        string fldPoster, 
                        string fldAbstract, 
                        string fldInformation, 
                        int fldSumVotes, 
                        int fldCountVotes, 
                        short fldSection, 
                        string fldTime, 
                        short fldfk_KindOfferID, 
                        string fldKindOfferName, 
                        short fldfk_CountryProductID, 
                        string fldCountryProductName, 
                        short fldfk_QualityID, 
                        string fldQualityName, 
                        short fldfk_RankID, 
                        string fldRankName, 
                        int fldPrice, 
                        string fldComment, 
                        short fldLanguageID, 
                        string fldLanguageName, 
                        short fldGenreID, 
                        string fldGenreName, 
                        short fldSubtitlesID, 
                        string fldSubtitlesName) {
                vSingleFilmRow rowvSingleFilmRow = ((vSingleFilmRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        fldFilmID,
                        fldFarsiName,
                        fldEnglishName,
                        fldActors,
                        fldDirector,
                        fldYearsOfProduct,
                        fldIMDBRating,
                        fldPoster,
                        fldAbstract,
                        fldInformation,
                        fldSumVotes,
                        fldCountVotes,
                        fldSection,
                        fldTime,
                        fldfk_KindOfferID,
                        fldKindOfferName,
                        fldfk_CountryProductID,
                        fldCountryProductName,
                        fldfk_QualityID,
                        fldQualityName,
                        fldfk_RankID,
                        fldRankName,
                        fldPrice,
                        fldComment,
                        fldLanguageID,
                        fldLanguageName,
                        fldGenreID,
                        fldGenreName,
                        fldSubtitlesID,
                        fldSubtitlesName};
                rowvSingleFilmRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowvSingleFilmRow);
                return rowvSingleFilmRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                vSingleFilmDataTable cln = ((vSingleFilmDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new vSingleFilmDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnfldFilmID = base.Columns["fldFilmID"];
                this.columnfldFarsiName = base.Columns["fldFarsiName"];
                this.columnfldEnglishName = base.Columns["fldEnglishName"];
                this.columnfldActors = base.Columns["fldActors"];
                this.columnfldDirector = base.Columns["fldDirector"];
                this.columnfldYearsOfProduct = base.Columns["fldYearsOfProduct"];
                this.columnfldIMDBRating = base.Columns["fldIMDBRating"];
                this.columnfldPoster = base.Columns["fldPoster"];
                this.columnfldAbstract = base.Columns["fldAbstract"];
                this.columnfldInformation = base.Columns["fldInformation"];
                this.columnfldSumVotes = base.Columns["fldSumVotes"];
                this.columnfldCountVotes = base.Columns["fldCountVotes"];
                this.columnfldSection = base.Columns["fldSection"];
                this.columnfldTime = base.Columns["fldTime"];
                this.columnfldfk_KindOfferID = base.Columns["fldfk_KindOfferID"];
                this.columnfldKindOfferName = base.Columns["fldKindOfferName"];
                this.columnfldfk_CountryProductID = base.Columns["fldfk_CountryProductID"];
                this.columnfldCountryProductName = base.Columns["fldCountryProductName"];
                this.columnfldfk_QualityID = base.Columns["fldfk_QualityID"];
                this.columnfldQualityName = base.Columns["fldQualityName"];
                this.columnfldfk_RankID = base.Columns["fldfk_RankID"];
                this.columnfldRankName = base.Columns["fldRankName"];
                this.columnfldPrice = base.Columns["fldPrice"];
                this.columnfldComment = base.Columns["fldComment"];
                this.columnfldLanguageID = base.Columns["fldLanguageID"];
                this.columnfldLanguageName = base.Columns["fldLanguageName"];
                this.columnfldGenreID = base.Columns["fldGenreID"];
                this.columnfldGenreName = base.Columns["fldGenreName"];
                this.columnfldSubtitlesID = base.Columns["fldSubtitlesID"];
                this.columnfldSubtitlesName = base.Columns["fldSubtitlesName"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnfldFilmID = new global::System.Data.DataColumn("fldFilmID", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldFilmID);
                this.columnfldFarsiName = new global::System.Data.DataColumn("fldFarsiName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldFarsiName);
                this.columnfldEnglishName = new global::System.Data.DataColumn("fldEnglishName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldEnglishName);
                this.columnfldActors = new global::System.Data.DataColumn("fldActors", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldActors);
                this.columnfldDirector = new global::System.Data.DataColumn("fldDirector", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldDirector);
                this.columnfldYearsOfProduct = new global::System.Data.DataColumn("fldYearsOfProduct", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldYearsOfProduct);
                this.columnfldIMDBRating = new global::System.Data.DataColumn("fldIMDBRating", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldIMDBRating);
                this.columnfldPoster = new global::System.Data.DataColumn("fldPoster", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldPoster);
                this.columnfldAbstract = new global::System.Data.DataColumn("fldAbstract", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldAbstract);
                this.columnfldInformation = new global::System.Data.DataColumn("fldInformation", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldInformation);
                this.columnfldSumVotes = new global::System.Data.DataColumn("fldSumVotes", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldSumVotes);
                this.columnfldCountVotes = new global::System.Data.DataColumn("fldCountVotes", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldCountVotes);
                this.columnfldSection = new global::System.Data.DataColumn("fldSection", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldSection);
                this.columnfldTime = new global::System.Data.DataColumn("fldTime", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldTime);
                this.columnfldfk_KindOfferID = new global::System.Data.DataColumn("fldfk_KindOfferID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldfk_KindOfferID);
                this.columnfldKindOfferName = new global::System.Data.DataColumn("fldKindOfferName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldKindOfferName);
                this.columnfldfk_CountryProductID = new global::System.Data.DataColumn("fldfk_CountryProductID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldfk_CountryProductID);
                this.columnfldCountryProductName = new global::System.Data.DataColumn("fldCountryProductName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldCountryProductName);
                this.columnfldfk_QualityID = new global::System.Data.DataColumn("fldfk_QualityID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldfk_QualityID);
                this.columnfldQualityName = new global::System.Data.DataColumn("fldQualityName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldQualityName);
                this.columnfldfk_RankID = new global::System.Data.DataColumn("fldfk_RankID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldfk_RankID);
                this.columnfldRankName = new global::System.Data.DataColumn("fldRankName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldRankName);
                this.columnfldPrice = new global::System.Data.DataColumn("fldPrice", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldPrice);
                this.columnfldComment = new global::System.Data.DataColumn("fldComment", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldComment);
                this.columnfldLanguageID = new global::System.Data.DataColumn("fldLanguageID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldLanguageID);
                this.columnfldLanguageName = new global::System.Data.DataColumn("fldLanguageName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldLanguageName);
                this.columnfldGenreID = new global::System.Data.DataColumn("fldGenreID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldGenreID);
                this.columnfldGenreName = new global::System.Data.DataColumn("fldGenreName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldGenreName);
                this.columnfldSubtitlesID = new global::System.Data.DataColumn("fldSubtitlesID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldSubtitlesID);
                this.columnfldSubtitlesName = new global::System.Data.DataColumn("fldSubtitlesName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfldSubtitlesName);
                this.columnfldFilmID.AllowDBNull = false;
                this.columnfldFarsiName.AllowDBNull = false;
                this.columnfldFarsiName.MaxLength = 200;
                this.columnfldEnglishName.AllowDBNull = false;
                this.columnfldEnglishName.MaxLength = 200;
                this.columnfldActors.MaxLength = 500;
                this.columnfldDirector.MaxLength = 100;
                this.columnfldYearsOfProduct.MaxLength = 4;
                this.columnfldPoster.MaxLength = 300;
                this.columnfldAbstract.MaxLength = 4000;
                this.columnfldInformation.MaxLength = 200;
                this.columnfldTime.MaxLength = 10;
                this.columnfldfk_KindOfferID.AllowDBNull = false;
                this.columnfldKindOfferName.MaxLength = 10;
                this.columnfldCountryProductName.MaxLength = 20;
                this.columnfldQualityName.MaxLength = 100;
                this.columnfldRankName.MaxLength = 50;
                this.columnfldComment.MaxLength = 4000;
                this.columnfldLanguageName.MaxLength = 50;
                this.columnfldGenreName.MaxLength = 50;
                this.columnfldSubtitlesName.MaxLength = 50;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmRow NewvSingleFilmRow() {
                return ((vSingleFilmRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new vSingleFilmRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(vSingleFilmRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.vSingleFilmRowChanged != null)) {
                    this.vSingleFilmRowChanged(this, new vSingleFilmRowChangeEvent(((vSingleFilmRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.vSingleFilmRowChanging != null)) {
                    this.vSingleFilmRowChanging(this, new vSingleFilmRowChangeEvent(((vSingleFilmRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.vSingleFilmRowDeleted != null)) {
                    this.vSingleFilmRowDeleted(this, new vSingleFilmRowChangeEvent(((vSingleFilmRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.vSingleFilmRowDeleting != null)) {
                    this.vSingleFilmRowDeleting(this, new vSingleFilmRowChangeEvent(((vSingleFilmRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovevSingleFilmRow(vSingleFilmRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SingleFilmDS ds = new SingleFilmDS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "vSingleFilmDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class vSingleFilmRow : global::System.Data.DataRow {
            
            private vSingleFilmDataTable tablevSingleFilm;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal vSingleFilmRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablevSingleFilm = ((vSingleFilmDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long fldFilmID {
                get {
                    return ((long)(this[this.tablevSingleFilm.fldFilmIDColumn]));
                }
                set {
                    this[this.tablevSingleFilm.fldFilmIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldFarsiName {
                get {
                    return ((string)(this[this.tablevSingleFilm.fldFarsiNameColumn]));
                }
                set {
                    this[this.tablevSingleFilm.fldFarsiNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldEnglishName {
                get {
                    return ((string)(this[this.tablevSingleFilm.fldEnglishNameColumn]));
                }
                set {
                    this[this.tablevSingleFilm.fldEnglishNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldActors {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldActorsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldActors\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldActorsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldDirector {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldDirectorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldDirector\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldDirectorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldYearsOfProduct {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldYearsOfProductColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldYearsOfProduct\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldYearsOfProductColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double fldIMDBRating {
                get {
                    try {
                        return ((double)(this[this.tablevSingleFilm.fldIMDBRatingColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldIMDBRating\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldIMDBRatingColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldPoster {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldPosterColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldPoster\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldPosterColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldAbstract {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldAbstractColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldAbstract\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldAbstractColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldInformation {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldInformationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldInformation\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldInformationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int fldSumVotes {
                get {
                    try {
                        return ((int)(this[this.tablevSingleFilm.fldSumVotesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldSumVotes\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldSumVotesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int fldCountVotes {
                get {
                    try {
                        return ((int)(this[this.tablevSingleFilm.fldCountVotesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldCountVotes\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldCountVotesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldSection {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldSectionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldSection\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldSectionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldTime {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldTime\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldfk_KindOfferID {
                get {
                    return ((short)(this[this.tablevSingleFilm.fldfk_KindOfferIDColumn]));
                }
                set {
                    this[this.tablevSingleFilm.fldfk_KindOfferIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldKindOfferName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldKindOfferNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldKindOfferName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldKindOfferNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldfk_CountryProductID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldfk_CountryProductIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldfk_CountryProductID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldfk_CountryProductIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldCountryProductName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldCountryProductNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldCountryProductName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldCountryProductNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldfk_QualityID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldfk_QualityIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldfk_QualityID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldfk_QualityIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldQualityName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldQualityNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldQualityName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldQualityNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldfk_RankID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldfk_RankIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldfk_RankID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldfk_RankIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldRankName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldRankNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldRankName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldRankNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int fldPrice {
                get {
                    try {
                        return ((int)(this[this.tablevSingleFilm.fldPriceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldPrice\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldPriceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldComment {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldCommentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldComment\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldCommentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldLanguageID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldLanguageIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldLanguageID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldLanguageIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldLanguageName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldLanguageNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldLanguageName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldLanguageNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldGenreID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldGenreIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldGenreID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldGenreIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldGenreName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldGenreNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldGenreName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldGenreNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short fldSubtitlesID {
                get {
                    try {
                        return ((short)(this[this.tablevSingleFilm.fldSubtitlesIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldSubtitlesID\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldSubtitlesIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fldSubtitlesName {
                get {
                    try {
                        return ((string)(this[this.tablevSingleFilm.fldSubtitlesNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fldSubtitlesName\' in table \'vSingleFilm\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevSingleFilm.fldSubtitlesNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldActorsNull() {
                return this.IsNull(this.tablevSingleFilm.fldActorsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldActorsNull() {
                this[this.tablevSingleFilm.fldActorsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldDirectorNull() {
                return this.IsNull(this.tablevSingleFilm.fldDirectorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldDirectorNull() {
                this[this.tablevSingleFilm.fldDirectorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldYearsOfProductNull() {
                return this.IsNull(this.tablevSingleFilm.fldYearsOfProductColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldYearsOfProductNull() {
                this[this.tablevSingleFilm.fldYearsOfProductColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldIMDBRatingNull() {
                return this.IsNull(this.tablevSingleFilm.fldIMDBRatingColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldIMDBRatingNull() {
                this[this.tablevSingleFilm.fldIMDBRatingColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldPosterNull() {
                return this.IsNull(this.tablevSingleFilm.fldPosterColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldPosterNull() {
                this[this.tablevSingleFilm.fldPosterColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldAbstractNull() {
                return this.IsNull(this.tablevSingleFilm.fldAbstractColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldAbstractNull() {
                this[this.tablevSingleFilm.fldAbstractColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldInformationNull() {
                return this.IsNull(this.tablevSingleFilm.fldInformationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldInformationNull() {
                this[this.tablevSingleFilm.fldInformationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldSumVotesNull() {
                return this.IsNull(this.tablevSingleFilm.fldSumVotesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldSumVotesNull() {
                this[this.tablevSingleFilm.fldSumVotesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldCountVotesNull() {
                return this.IsNull(this.tablevSingleFilm.fldCountVotesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldCountVotesNull() {
                this[this.tablevSingleFilm.fldCountVotesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldSectionNull() {
                return this.IsNull(this.tablevSingleFilm.fldSectionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldSectionNull() {
                this[this.tablevSingleFilm.fldSectionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldTimeNull() {
                return this.IsNull(this.tablevSingleFilm.fldTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldTimeNull() {
                this[this.tablevSingleFilm.fldTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldKindOfferNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldKindOfferNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldKindOfferNameNull() {
                this[this.tablevSingleFilm.fldKindOfferNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfldfk_CountryProductIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldfk_CountryProductIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfldfk_CountryProductIDNull() {
                this[this.tablevSingleFilm.fldfk_CountryProductIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldCountryProductNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldCountryProductNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldCountryProductNameNull() {
                this[this.tablevSingleFilm.fldCountryProductNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfldfk_QualityIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldfk_QualityIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfldfk_QualityIDNull() {
                this[this.tablevSingleFilm.fldfk_QualityIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldQualityNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldQualityNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldQualityNameNull() {
                this[this.tablevSingleFilm.fldQualityNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfldfk_RankIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldfk_RankIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfldfk_RankIDNull() {
                this[this.tablevSingleFilm.fldfk_RankIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldRankNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldRankNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldRankNameNull() {
                this[this.tablevSingleFilm.fldRankNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldPriceNull() {
                return this.IsNull(this.tablevSingleFilm.fldPriceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldPriceNull() {
                this[this.tablevSingleFilm.fldPriceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldCommentNull() {
                return this.IsNull(this.tablevSingleFilm.fldCommentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldCommentNull() {
                this[this.tablevSingleFilm.fldCommentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldLanguageIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldLanguageIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldLanguageIDNull() {
                this[this.tablevSingleFilm.fldLanguageIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldLanguageNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldLanguageNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldLanguageNameNull() {
                this[this.tablevSingleFilm.fldLanguageNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldGenreIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldGenreIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldGenreIDNull() {
                this[this.tablevSingleFilm.fldGenreIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldGenreNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldGenreNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldGenreNameNull() {
                this[this.tablevSingleFilm.fldGenreNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldSubtitlesIDNull() {
                return this.IsNull(this.tablevSingleFilm.fldSubtitlesIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldSubtitlesIDNull() {
                this[this.tablevSingleFilm.fldSubtitlesIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfldSubtitlesNameNull() {
                return this.IsNull(this.tablevSingleFilm.fldSubtitlesNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfldSubtitlesNameNull() {
                this[this.tablevSingleFilm.fldSubtitlesNameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class vSingleFilmRowChangeEvent : global::System.EventArgs {
            
            private vSingleFilmRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmRowChangeEvent(vSingleFilmRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public vSingleFilmRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591